doctrine:
     orm:
         dql:
             datetime_functions:
                 day: DoctrineExtensions\Query\Mysql\Day
                 month: DoctrineExtensions\Query\Mysql\Month
                 year: DoctrineExtensions\Query\Mysql\Year