name: "Static Analysis"

on:
  pull_request:
    branches:
      - "master"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - psalm*
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - psalm*

jobs:
  static-analysis:
    uses: "doctrine/.github/.github/workflows/static-analysis.yml@4.0.0"
